//Pustynna Burza
class gct_usm_soldier_80s_d: usm_soldier_80s_d {
	author = "Delta Hawk";
	editorPreview = "\gct_extrastuff\data\icons\logo_gct.jpg";
	scope = 2;
	scopeCurator = 2;
	scopeArsenal = 2;
	faction = "gct_units";
	editorSubcategory = "gct_usm_usmc_80s_d";	
};
class gct_usm_soldier_80s_d_h_co: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Oficer";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_officer_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_sl: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Dowódca Drużyny";
	//picture = "\us_military_units\icons\pic_nco_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_leader_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_tl: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Dowódca Sekcji";
	//picture = "\us_military_units\icons\pic_nco_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_leader_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "SmokeShellred", "smokeshellpurple", "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_grenadier: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Grenadier";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2_gl"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2_gl"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareWhite_F", "UGL_FlareWhite_F"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareWhite_F", "UGL_FlareWhite_F"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_gr", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_gr", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_m249: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Celowniczy (M249)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_machinegunner_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_abag_m60";
	weapons[] = {"Throw", "Put", "CUP_lmg_M249"};
	respawnWeapons[] = {"Throw", "Put", "CUP_lmg_M249"};
	magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
	respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_rifleman: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Strzelec (M16A2)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_riflemanat: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Strzelec (M136)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_M136"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_M136"};
	magazines[] = {"CUP_M136_M", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"CUP_M136_M", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_medic: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Medyk";
	//picture = "\us_military_units\icons\i_med_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_medic_ca.paa";
	attendant = 1;
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_m5_medic";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_rto: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Radzik";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_st138_prc77";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_m240: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Celowniczy (M240)";
	//picture = "\us_military_units\icons\pic_mg_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_machinegunner_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_762x51_bandoliers";
	weapons[] = {"Throw", "Put", "CUP_lmg_M240"};
	respawnWeapons[] = {"Throw", "Put", "CUP_lmg_M240"};
	magazines[] = {"rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51"};
	respawnMagazines[] = {"rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_m240_ass: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Asystent (M240)";
	//picture = "\us_military_units\icons\pic_amg_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_abag_m60";
	weapons[] = {"Throw", "Put", "gst_m16a2","Binocular"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2","Binocular"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_m240_ass2: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Amunicyjny (M240)";
	//picture = "\us_military_units\icons\pic_mgab_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_762x51_bandoliers";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_javelin: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "AT Specjalista (Javelin)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fgm148"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fgm148"};
	magazines[] = {"rhs_fgm148_magazine_AT", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_fgm148_magazine_AT", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_javelin_ass: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "AT Asystent (Javelin)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_aa: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "AA Specjalista (Stinger)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fim92"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fim92"};
	magazines[] = {"rhs_fim92_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_fim92_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_pasgtdes_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_h_crew1: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Zalogant, Ciezki";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put"};
	respawnWeapons[] = {"Throw", "Put"};
	magazines[] = {};
	respawnMagazines[] = {};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des"};
	linkedItems[] = {"usm_helmet_cvc", "usm_vest_pasgt", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_cvc", "usm_vest_pasgt", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_pilot: gct_usm_soldier_80s_d {
	author = "Keeway";
	scope = 0;
	scopeCurator = 0;
	scopeArsenal = 0;
	displayName = "Pilot, Smiglo";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put"};
	respawnWeapons[] = {"Throw", "Put"};
	magazines[] = {};
	respawnMagazines[] = {};
	Items[] = {};
	RespawnItems[] = {};
};
//Pustynna burza na lekko
class gct_usm_soldier_80s_d_l_co: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Oficer (lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_officer_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_sl: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Dowódca Drużyny (lekki)";
	//picture = "\us_military_units\icons\pic_nco_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_leader_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_tl: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Dowódca Sekcji (lekki)";
	//picture = "\us_military_units\icons\pic_nco_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_leader_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "SmokeShellred", "smokeshellpurple", "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","ACE_Flashlight_XL50","ACE_MapTools","ACRE_PRC148","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_grenadier: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Grenadier (lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2_gl"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2_gl"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareWhite_F", "UGL_FlareWhite_F"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareWhite_F", "UGL_FlareWhite_F"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_gr", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_gr", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_m249: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Celowniczy (M249, lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_machinegunner_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_abag_m60";
	weapons[] = {"Throw", "Put", "CUP_lmg_M249"};
	respawnWeapons[] = {"Throw", "Put", "CUP_lmg_M249"};
	magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
	respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_rifleman: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Strzelec (M16A2, lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_riflemanat: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Strzelec (M136, lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_M136"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_M136"};
	magazines[] = {"CUP_M136_M", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"CUP_M136_M", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_medic: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Medyk (lekki)";
	//picture = "\us_military_units\icons\i_med_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_medic_ca.paa";
	attendant = 1;
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_m5_medic";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_rto: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Radzik (lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_st138_prc77";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_m240: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Celowniczy (M240, lekki)";
	//picture = "\us_military_units\icons\pic_mg_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_machinegunner_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_762x51_bandoliers";
	weapons[] = {"Throw", "Put", "CUP_lmg_M240"};
	respawnWeapons[] = {"Throw", "Put", "CUP_lmg_M240"};
	magazines[] = {"rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51"};
	respawnMagazines[] = {"rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51", "rhsusf_50Rnd_762x51","rhsusf_50Rnd_762x51"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_mg", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_m240_ass: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Asystent (M240, lekki)";
	//picture = "\us_military_units\icons\pic_amg_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_abag_m60";
	weapons[] = {"Throw", "Put", "gst_m16a2","Binocular"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2","Binocular"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_m240_ass2: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "KM Amunicyjny (M240, lekki)";
	//picture = "\us_military_units\icons\pic_mgab_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "usm_pack_762x51_bandoliers";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_javelin: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "AT Asystent (Javelin, lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fgm148"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fgm148"};
	magazines[] = {"rhs_fgm148_magazine_AT", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_fgm148_magazine_AT", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_javelin_ass: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "AT Asystent (Javelin, lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2"};
	magazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_aa: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "AA Specjalista (Stinger, lekki)";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fim92"};
	respawnWeapons[] = {"Throw", "Put", "gst_m16a2", "rhs_weap_fim92"};
	magazines[] = {"rhs_fim92_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	respawnMagazines[] = {"rhs_fim92_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "rhs_mag_30Rnd_556x45_Mk262_Stanag", "SmokeShell",  "rhs_mag_m67", "rhs_mag_m67"};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des", "rhsusf_ANPVS_14"};
	linkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_pasgt_g_d", "usm_vest_lbe_rm", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};
class gct_usm_soldier_80s_d_l_crew1: gct_usm_soldier_80s_d {
	author = "Keeway";
	displayName = "Zalogant, Lekki";
	//picture = "\us_military_units\icons\i_null_ca.paa";
	portrait = "\us_military_units\icons\p_army.paa";
	icon = "\us_military_units\icons\i_soldier_ca.paa";
	uniformClass = "usm_bdu_d";
	backpack = "";
	weapons[] = {"Throw", "Put"};
	respawnWeapons[] = {"Throw", "Put"};
	magazines[] = {};
	respawnMagazines[] = {};
	Items[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des"};
	RespawnItems[] = {"ACE_CableTie","ACE_EarPlugs","ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing","ACE_morphine","usm_bdu_boonie_des"};
	linkedItems[] = {"usm_helmet_cvc", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	respawnLinkedItems[] = {"usm_helmet_cvc", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
};